---
- name: Simple IOS Playbook
  hosts: myrouters
  gather_facts: no

  vars:
    username: admin1
    hostname: "{{ inventory_hostname }}"
    ip_addr: "{{ IP2 }}"

  tasks:

    - name: Create User
      cisco.ios.ios_user:
        name: "{{ username }}"
        nopassword: true
        privilege: 15
        state: present

    - name: Configure Login Banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          Welcome to {{ hostname }}
          Authorized Users Only
        state: present

    - name: Configure Interface IP
      cisco.ios.ios_config:
        parents: interface GigabitEthernet2
        lines:
          - description Connected_by_Ansible
          - ip address {{ ip_addr }} 255.255.255.0
          - no shutdown

    - name: Create VLAN 10
      cisco.ios.ios_vlans:
        config:
          - vlan_id: 10
            name: USERS
        state: merged

    - name: Configure Access Port
      cisco.ios.ios_config:
        parents: interface GigabitEthernet1
        lines:
          - switchport mode access
          - switchport access vlan 10

    - name: Configure Hostname
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ hostname }}"
        state: merged



